[versions]
junit-jupiter = "5.10.3"
junit-platform = "1.10.3"
jetbrains-annotations = "26.0.1"

adventure = "4.25.0"
adventure-platform-fabric = "6.2.0"
adventure-platform-neoforge = "6.8.0"

fabric-api = "0.138.4+1.21.10"
minecraft = "1.21.10"
fabric-loader = "0.18.3"
fabric-loom = "1.11.7"

snakeyaml = "2.0"
gson = "2.10.1"
slf4j = "2.0.7"
asm = "9.7.1"
brigadier = "1.0.18"

paper-api = "1.21.10-R0.1-SNAPSHOT"
userdev = "2.0.0-beta.19"
velocity-api = "3.4.0-SNAPSHOT"
neoforge = "21.10.64"
neoforge-moddev = "2.0.137"

shadow = "9.0.0-beta8"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

userdev = { id = "io.papermc.paperweight.userdev", version.ref = "userdev" }    
neoforge-moddev = { id = "net.neoforged.moddev", version.ref = "neoforge-moddev" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }

annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }

adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventure-platform-fabric = { module = "net.kyori:adventure-platform-fabric", version.ref = "adventure-platform-fabric" }
adventure-platform-neoforge = { module = "net.kyori:adventure-platform-neoforge", version.ref = "adventure-platform-neoforge" }

fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }

asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-commons = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
asm-analysis = { module = "org.ow2.asm:asm-analysis", version.ref = "asm" }

paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }

velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity-api" }

spool = { module = "de.t14d3:spool", version = "1.2-SNAPSHOT" }
